name: Lint Commit & Codes
on: 
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v3

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - uses: wearerequired/lint-action@v1
        with:
          eslint: true
          continue_on_error: false
          auto_fix: false
